### PR TITLE
Json schema to provide coding assistance for goss.yaml in IDEs

### PR DESCRIPTION
**Pull request by gberche-orange**
The json schema when configured in IDEs (see updated README.md for Intellij instructions) providers coding assistance for editing and authoring goss.yaml files

including: 
* completion
image
* inline doc in text or html format for long examples
image
* inspection such as required properties
image

##### Checklist

- [ ] `make test-all` (UNIX) passes. CI will also test this
- [ ] unit and/or integration tests are included (if applicable)
- [x] documentation is changed or added (if applicable)

### Description of change

* adds a json schema file in yaml format
* addsa a sample goss.yaml file gathering most currently documented examples. Used for testing the json schema

Limitations:
- coverage for matchers is still low. 
- advanced matchers are not yet modeled
- templates likely can't be supported by json schema, and the source document isn't valid yaml

### CODE REVIEW

**Comment by ripienaar** [comment]
This is amazing, I've wanted to do something like this myself but always seemed too much work.  Do you generate it somehow or hand built?

**Comment by gberche-orange** [comment]
Thanks, this is hand built but with coding assistance from intellij it goes pretty fast.

**Comment by aelsabbahy** [comment]
Reran Travis, if was an intermittent network issue that caused the failure.

**Comment by aelsabbahy** [comment]
Does the auto complete work with all the gomega conditions?

**Review by ripienaar — APPROVED** [review]
LGTM

**Review by aelsabbahy — APPROVED** [review]
Thank you for taking the time to contribute this.

**Comment by gberche-orange** [comment]
@aelsabbahy 
> This looks very cool. Out of curiosity, when doing templates or advanced matchers does it just fail completely or is it somewhat graceful?

Advanced matchers are gracefully ignored. I think it would be possible to refine the Json schema to include gomega supported matchers 

For templates, unfortunately the goss documents with templates are not valid json/yaml, so the plain json can't do much yet.

image

A useful workaround would be to find a way to actually render the templates into a valid goss rendered yaml document. This way, the json validation step could be applied after a template pre-rendering step, still providing useful feedback.

I'll submit a new PR with few fixes soon, and possibly would explore those ideas. 

Thanks for your quick feedback and merge (I'm just getting back from Christmas breaks)

**Comment by gberche-orange** [comment]
Submitted https://github.com/goss-org/goss/pull/795 with rendering preprocessing step using the `render` command

**Pull request merged**
