### PR TITLE
ci: add schedule for trivy scans

### PR DESCRIPTION
**Pull request by dklimpel**
##### Checklist

- [x] `make test-all` (UNIX) passes. CI will also test this
- [x] unit and/or integration tests are included (if applicable)
- [ ] documentation is changed or added (if applicable)

### Description of change

A schedule task to scan `latest` container image (with latest tagged binary).

At the moment there is no `latest` image and this PR has to wait for next tagged version.

### CODE REVIEW

**Comment by aelsabbahy** [comment]
I'm thinking of cutting a release this weekend to address the open CVE, also thinking of getting one last release in before the Travis cutover.. in case we run into unexpected turbulence.

I assume this PR will have to wait until after the release?

**Comment by dklimpel** [comment]
> I assume this PR will have to wait until after the release?

Yes.

> also thinking of getting one last release in before the Travis cutover.. in case we run into unexpected turbulence

Sounds good.

**Comment by dklimpel** [comment]
There is a version tagged with `latest` to scan per schedule, now.

**Review by aelsabbahy — APPROVED** [review]

**Comment by aelsabbahy** [comment]
Awesome, thanks!

**Pull request merged**
