### PR TITLE
Updated go version in deps and CI.

### PR DESCRIPTION
**Pull request by AlexSkrypnyk**
##### Checklist

- [x] `make test-all` (UNIX) passes. CI will also test this
- [ ] unit and/or integration tests are included (if applicable)
- [ ] documentation is changed or added (if applicable)

### Description of change
- Updated to go `1.20`
- Updated dependencies

The binaries in the latest release rely on `stdlib:18.5` that has some CVEs.

Cursor_and_Image_Layer_Details_-_drevops_ci-builder_preview_1_6_0___Docker_Hub

### CODE REVIEW

**Review by aelsabbahy — APPROVED** [review]

**Comment by aelsabbahy** [comment]
Totally dropped the ball on this. I'll take care of it this week.

Apologies for the delay.

**Comment by aelsabbahy** [comment]
Curious, what are you using to test for vulnerabilities. I'm surprised dependabot didn't submit a PR 😢

**Comment by aelsabbahy** [comment]
Released: https://github.com/goss-org/goss/releases/tag/v0.3.22

Thank you for the PR, much appreciated!

**Comment by AlexSkrypnyk** [comment]
@aelsabbahy 
I used Docker scout in Docker HUB web UI as a part of the image that uses Goss. 

Thank you for merging and releasing this!

**Pull request merged**
