### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ripienaar**
##### Checklist

- [x] `make test-all` (UNIX) passes. CI will also test this
- [x] unit and/or integration tests are included (if applicable)
- [x] documentation is changed or added (if applicable)

### Description of change

Dependency updates - mainly to get the new sprig release which in turns resolves a long standing issue after `mergo` renamed itself.

### CODE REVIEW

**Comment by ripienaar** [comment]
I dont think these failures have anything to do with me change

**Comment by aelsabbahy** [comment]
Probably not, CI is like 95% transitioned to GHA. Going to merge this, looks great!

Can you add a link to the mergo sprig issue.. curious to learn more about it.

**Review by aelsabbahy — APPROVED** [review]

**Comment by ripienaar** [comment]
Mergo renamed itself. Many projects adopted the new name but sprig had no releases for ages. This caused go mode to fail badly 

fir me sprig and goss were the last dependencies that didn’t move yet so now things should be better

https://github.com/darccio/mergo/releases/tag/v1.0.0

**Comment by aelsabbahy** [comment]
Cool, thanks for the link. I haven't run into too many go dependency quirks.. but perhaps I've just gotten lucky so far. 🤷

**Pull request merged**
