### PR TITLE
added skipped count in json output format

### PR DESCRIPTION
**Pull request by sandeepsharmadevops**
##### Checklist

- [ ] `make test-all` (UNIX) passes. CI will also test this
- [ ] unit and/or integration tests are included (if applicable)
- [ ] documentation is changed or added (if applicable)

### CODE REVIEW

**Comment by sandeepsharmadevops** [comment]
@aelsabbahy Please share your review comments, if changes made won't impact the overall or any specific goss functionalities, let me know in case of any otherwise.

Thanks!!

**Review by ripienaar — APPROVED** [review]
Looks good to me, I think I had a branch here that was essentially the same but never pushed it.

**Comment by sandeepsharmadevops** [comment]
> Looks good to me, I think I had a branch here that was essentially the same but never pushed it.

Thanks for looking into @ripienaar, it will be really helpful, if these changes can be merged and release a new version as GA.

Thanks!!

**Review by aelsabbahy — APPROVED** [review]
CI had some intermittent failures, toon a couple of retri s to get it green. Will release over the weekend.

Thank you for the contribution!

**Comment by aelsabbahy** [comment]
released: https://github.com/goss-org/goss/releases/tag/v0.3.23

**Pull request merged**
