### PR TITLE
Add uid/gid check in file module

### PR DESCRIPTION
**Pull request by smutel**
##### Checklist

- [ X] `make test-all` (UNIX) passes. CI will also test this
- [ X] unit and/or integration tests are included (if applicable)
- [ X] documentation is changed or added (if applicable)

### Description of change

Add UID/GID check for file module
For my purpose I need to check the uid/gid instead of the owner/group

### CODE REVIEW

**Review by aelsabbahy — APPROVED** [review]
Cool addition, thank you for taking the time to implement this!

**Comment by smutel** [comment]
Thank you to have merged my PR.
Do you have plan a new release soon ?

**Comment by aelsabbahy** [comment]
Tried to cut a release today, but running into travis-ci issues with their deploy plugin.


```
** Updating RubyGems to the latest compatible version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
dpl.1
Installing deploy dependencies
ERROR:  Error installing dpl-releases:
	multipart-post requires Ruby version >= 2.5.0.
Successfully installed public_suffix-3.0.3
Successfully installed mime-types-data-3.2024.0305
Successfully installed mime-types-3.5.2
/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dpl/provider/releases (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/lib/dpl/provider.rb:93:in `rescue in block in new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/lib/dpl/provider.rb:68:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/lib/dpl/provider.rb:67:in `new'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.16/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
failed to deploy
```

I haven't seen this issue before, I'll dig into it in the coming days, but unfortunately I'm currently blocked on deploying from travis-ci.

**Comment by smutel** [comment]
Some links related to your issue:
* https://travis-ci.community/t/github-release-fail-after-ruby-version-update/13214/12
* https://travis-ci.community/t/github-pages-deployment-is-broken/3537

**Comment by aelsabbahy** [comment]
Fixed by #888

I've released v0.4.6 which includes this change. Apologies for the delay, I'm on paternity leave so not on a computer often.

**Pull request merged**
